# Generated by Django 3.2.7 on 2021-09-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الصندوق')),
                ('image', models.ImageField(upload_to='boxes', verbose_name='الصورة')),
                ('price', models.FloatField(verbose_name='السعر')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الصندوق')),
                ('image', models.ImageField(upload_to='boxes', verbose_name='الصورة')),
                ('price', models.FloatField(verbose_name='السعر')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('boxes', models.ManyToManyField(to='root.Box', verbose_name='الصناديق')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='products',
            field=models.ManyToManyField(to='root.Product', verbose_name='المنتجات'),
        ),
    ]
