# Generated by Django 3.2.7 on 2021-09-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='النوع'),
        ),
    ]
