# Generated by Django 3.2.7 on 2021-09-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20210906_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='boxes',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons', verbose_name='الصورة'),
        ),
    ]
