# Generated by Django 3.2.7 on 2021-09-10 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_auto_20210910_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_number', models.IntegerField(verbose_name='رقم الللفة')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.message', verbose_name='الرسالة'),
        ),
        migrations.AddField(
            model_name='product',
            name='spin_number',
            field=models.ManyToManyField(to='root.SpinNumber', verbose_name='رقم اللفات'),
        ),
    ]
