# Generated by Django 3.2.7 on 2021-09-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_auto_20210910_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spinnumber',
            options={'ordering': ['-spin_number']},
        ),
    ]
