# Generated by Django 3.2.7 on 2021-09-10 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_alter_spinnumber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spinnumber',
            options={'ordering': ['spin_number']},
        ),
    ]
