# Generated by Django 3.2.7 on 2021-09-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_alter_spinnumber_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='الصورة'),
        ),
    ]
