# Generated by Django 3.2.7 on 2021-09-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='balance',
            field=models.FloatField(blank=True, null=True, verbose_name='الرصيد'),
        ),
        migrations.AlterField(
            model_name='player',
            name='boxes_spin',
            field=models.ManyToManyField(blank=True, null=True, through='root.BoxSpin', to='root.Box', verbose_name='لفات الصناديق'),
        ),
        migrations.AlterField(
            model_name='player',
            name='prizes',
            field=models.ManyToManyField(blank=True, null=True, through='root.Prize', to='root.Product', verbose_name='الجوائز'),
        ),
    ]
