# Generated by Django 3.2.7 on 2021-09-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_auto_20210910_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='محتوي الرسالة'),
        ),
        migrations.AddField(
            model_name='message',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='لينك حساب الفيس'),
        ),
        migrations.AddField(
            model_name='message',
            name='google',
            field=models.URLField(blank=True, null=True, verbose_name='لينك حساب جوجل'),
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان الرسالة'),
        ),
        migrations.AddField(
            model_name='message',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='لينك حساب التويتر'),
        ),
    ]
