# Generated by Django 3.2.7 on 2021-09-14 00:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='لينك حساب الفيس')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='لينك حساب التويتر')),
                ('google', models.URLField(blank=True, null=True, verbose_name='لينك حساب جوجل')),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='message',
            name='google',
        ),
        migrations.RemoveField(
            model_name='message',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='محتوي الرسالة'),
        ),
    ]
